[package]
name = "icelake"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
description = "Pure Rust Iceberg Implementation"

[dependencies]
anyhow = "1.0.71"
apache-avro = { version = "0.14.0", features = ["derive"] }
futures = "0.3.28"
opendal = "0.37.0"
serde = "1.0.164"
serde_json = "1.0.96"
serde_with = "3.0.0"
tokio = { version = "1.28.2", features = ["full"] }

[[example]]
name = "read_iceberg_table"
harness = false