[package]
name = "icelake"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
description = "Pure Rust Iceberg Implementation"

[dependencies]
futures = "0.3.28"
opendal = "0.37.0"
serde = "1.0.164"
