[package]
name = "icelake"
version = "0.0.3"
edition = "2021"
license = "Apache-2.0"
description = "Pure Rust Iceberg Implementation"

[dependencies]
anyhow = "1"
apache-avro = { version = "0.14", features = ["derive"] }
futures = "0.3"
opendal = "0.37"
serde = "1"
serde_json = "1"
serde_with = "3"
tokio = { version = "1.28", features = ["full"] }

[[example]]
name = "read_iceberg_table"
harness = false
