[package]
name = "icelake"
version = "0.0.6"
edition = "2021"
license = "Apache-2.0"
description = "Pure Rust Iceberg Implementation"

[features]
arrow_schema = ["dep:arrow-schema"]
io_parquet = ["arrow_schema", "dep:parquet", "dep:arrow-array"]

[dependencies]
anyhow = "1"
async-trait = "0.1.68"
apache-avro = { version = "0.14", features = ["derive"] }
arrow-array = { version = ">=40", optional = true }
arrow-schema = { version = ">=40", optional = true }
bytes = "1.4.0"
futures = "0.3"
opendal = "0.38"
uuid = { version = "1", features = ["v4"] }
serde = "1"
serde_json = "1"
serde_with = "3"
tokio = { version = "1.28", features = ["full"] }
parquet = { version = ">=40", features = ["async"], optional = true }

[dev-dependencies]
once_cell = "1"

[[example]]
name = "read_iceberg_table"
harness = false
