[package]
name = "icelake"
version = "0.0.8"
edition = "2021"
license = "Apache-2.0"
description = "Pure Rust Iceberg Implementation"

[package.metadata.docs.rs]
all-features = true

[features]
arrow_schema = ["dep:arrow-schema"]
io_parquet = ["arrow_schema", "dep:parquet", "dep:arrow-array"]

[dependencies]
anyhow = "1"
async-trait = "0.1"
apache-avro = { version = "0.15", features = ["derive"] }
arrow-array = { version = ">=40, <44", optional = true }
arrow-schema = { version = ">=40, <44", optional = true }
bytes = "1"
futures = "0.3"
opendal = ">=0.37, <0.39"
uuid = { version = "1", features = ["v4"] }
serde = "1"
serde_json = "1"
serde_with = "3"
tokio = { version = "1.28", features = ["full"] }
parquet = { version = ">=40, <44", features = ["async"], optional = true }
rust_decimal = "1.30"
chrono = "0.4"
faster-hex = "0.8.0"
lazy_static = "1.4"

[dev-dependencies]
once_cell = "1"
tempfile = "3"

[[example]]
name = "read_iceberg_table"
harness = false
