version: "3"

services:
  trino:
    image: trinodb/trino
    container_name: trino
    user: root
    networks:
      iceberg_net:
    depends_on:
      - iceberg-rest
    ports:
      - 8080:8080
    volumes:
      - ./catalog:/etc/trino/catalog
      - iceberg_data:/data/trino/iceberg
  iceberg-rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    user: root
    networks:
      iceberg_net:
    ports:
      - 8181:8181
    environment:
      - CATALOG__IMPL=org.apache.iceberg.hadoop.HadoopCatalog
      - CATALOG_WAREHOUSE=file:///data/trino/iceberg
      - CATALOG_IO__IMPL=org.apache.iceberg.hadoop.HadoopFileIO
    volumes:
      - iceberg_data:/data/trino/iceberg
networks:
  iceberg_net:
volumes:
  iceberg_data:
