name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update Rust Stable
        run: rustup update stable

      - name: Format
        run: cargo fmt -p icelake  -- --check

      - name: Clippy
        run: cargo clippy --all-targets --workspace --all-features -- -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Rust Stable
        run: rustup update stable
      - name: Build
        run: cargo build --all-features

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Rust Stable
        run: rustup update stable
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.5.1"
      - name: Install dependencies
        run: |
          cd testdata/python
          poetry update --quiet
      - name: Test
        run: cargo test --all-targets --all-features